<?php
$userid = $this->session->userdata('id');
$usernames = $this->session->userdata('usernames');
$userid = $this->session->userdata('id');

$type="";
if($this->input->get('s_type')){
	$type=$this->input->get('s_type');
}
$status="";
if($this->input->get('status')){
	$status=$this->input->get('status');
}
$requestid="";
if($this->input->get('requestid')){
	$requestid=$this->input->get('requestid');
}
//01-01-2018 to 31-12-2018
$date1=date("Y")."-01-01";
$date2=date("Y-m-d");
if($this->input->get('date1')){
	$date1=$this->input->get('date1');
}
if($this->input->get('date2')){
	$date2=$this->input->get('date2');
}
$date11=$date1." 00:00:00";
$date22=$date2." 23:59:59";

$services = $this->entity->get_invoices($date11,$date22,$requestid,$status,"");
?>
<!--<link rel="stylesheet" href="<?php echo base_url()?>assets/public/datepicker/datepicker.css">-->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      
	  
	  <div class="row">
		<div class="col-md-5"><h5 class="text-primary" style="font-size:24px;font-weight:500">Invoices</h5></div>
		<!--
		<a class="btn bg-info margin" title="click here to request a new service" href="<?=base_url("services/new_request")?>"><i class="fa fa-plus"></i> Request For A New Service</a>
		-->
		<!--<div class="col-md-3"><h5 style="font-size:20px;font-weight:200">My Login ID: <?=$memberid?></h5></div>
		<div class="col-md-3">
			<h5 style="font-size:15px;font-weight:200">
				<b>Help Desk:</b> <i class="fa fa-phone"></i> 07032440565.
				<br>
				<i class="fa fa-envelope"></i> help@generators.com.ng
			</h5>
		</div>
		<div class="col-md-3">
			<a class="btn bg-info margin" title="click here to request a new service" href="<?=base_url("services/new_request")?>"><i class="fa fa-plus"></i> Request For A New Service</a>
		</div>
		-->
	  </div>
	  
	  <?=$this->utilities->get_bread_crumbs($crumb)?>
	  
	  
    </section>
	
    <!-- Main content -->
    <section class="content">
	
	
<?php
	echo $this->utilities->
		show_notification(
		$this->session->flashdata('flag'),
		$this->session->flashdata('message')
		);
?>


<?php
	$attributes = array(
	'name' => 'loginForm',
	'class' => 'form-signin',
	'data-parsley-validate' => ''
	);
	echo form_open('#', $attributes);
?>
<!-- Modal -->

<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-primary" id="myModalLabel" style="font-size:24px;font-weight:500"></h4>
      </div>
	
		<table class="table table-striped table-hover table-bordered rwd-table">
			<tr>
				<td align="left" width="30%"><b>Service Request ID:</b></td>
				<td align="left"><span id="service_request_id"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Total Amount:</b></td>
				<td align="left"><span id="total_amount"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Discount Amount:</b></td>
				<td align="left"><span id="discount_amount"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Invoice Amount:</b></td>
				<td align="left"><span id="invoice_amount"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Paid Amount:</b></td>
				<td align="left"><span id="paid_amount"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Balance Amount:</b></td>
				<td align="left"><span id="balance_amount"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Description:</b></td>
				<td align="left"><span id="description"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Invoice Status:</b></td>
				<td align="left"><span id="i_status"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Record Date:</b></td>
				<td align="left"><span id="record_date"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Generated On:</b></td>
				<td align="left"><span id="createdon"></span></td>
			</tr>
			<tr>
				<td align="left"><b>Generated By:</b></td>
				<td align="left"><span id="createdby"></span></td>
			</tr>
		</table>
		
      <div class="modal-footer">
		<input type="hidden" name="appid" id="appid" />
		<input type="hidden" name="emailval" id="emailval" />
		<input type="hidden" name="pass" id="pass" />
		<a target="_blank" id="btn_print" class="btn btn-primary">Print Invoice</a>
		<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<?php echo form_close(); ?>	  
	
	
<?php
	$attributes = array(
	'name' => 'loginForm',
	'class' => 'form-signin',
	'data-parsley-validate' => ''
	);
	echo form_open('#', $attributes);
?>
<!-- Modal -->

<div class="modal fade bs-example-modal-lg2" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-primary" id="myModalLabel2" style="font-size:24px;font-weight:500"></h4>
      </div>
		
		<img id="loadingimg" style="display:none;" src="<?=base_url("assets/user/img/spinner.gif")?>" alt='please wait...' />
		
		<div id="display_payments"></div>
		
      <div class="modal-footer">
		<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<?php echo form_close(); ?>	  

      <!-- Default box -->
	  
      <div class="box">
        <div class="box-body">
					
			<!--
			<div class="box-body">
				<div class="col-md-3 col-sm-6 col-xs-12">
				  <div class="info-box">
					<span class="info-box-icon bg-green"><i class="fa fa-clock-o"></i></span>
					<div class="info-box-content">
					  <span class="info-box-text">This Month<br/><?=date("F")?></span>
					  <span class="info-box-number">N</span>
					</div>
				  </div>
				</div>
				
				<div class="col-md-3 col-sm-6 col-xs-12">
				  <div class="info-box">
					<span class="info-box-icon bg-aqua"><i class="fa fa-clock-o"></i></span>
					<div class="info-box-content">
					  <span class="info-box-text">This Year<br/><?=date("Y")?></span>
					  <span class="info-box-number">N</span>
					</div>
				  </div>
				</div>
				
				<div class="col-md-3 col-sm-6 col-xs-12">
				  <div class="info-box">
					<span class="info-box-icon bg-red"><i class="fa fa-calendar"></i></span>
					<div class="info-box-content">
					  <span class="info-box-text">All <br>Time</span>
					  <span class="info-box-number">N</span>
					</div>
				  </div>
				</div>
				
				<div class="col-md-3 col-sm-6 col-xs-12">
				  <div class="info-box">
					<span class="info-box-icon bg-yellow"><i class="fa fa-calendar-check-o"></i></span>
					<div class="info-box-content">
					  <span class="info-box-text">All Time<br/>Transaction</span>
					  <span class="info-box-number"></span>
					</div>
				  </div>
				</div>
			</div>
			-->
			
			<hr style="margin-top:0px;margin-bottom:0px;border-top:2px solid #eee">
			<?php
				$attributes = array(
					'name' => 'loginForm',
					'id' => 'frmRegister',
					'class' => 'sky-form',
					'method' => 'GET',
					'data-parsley-validate' => ''
				);
				echo form_open('cpanel/invoices', $attributes);
			?>
			
			<div class="box-body text-center">
				<span style="font-size:22px;" class="text-primary">Displaying Records from <?=date("d-M-Y", strtotime($date1))?> to <?=date("d-M-Y", strtotime($date2))?></span>
			</div>
			<div class="box-body" style="">
				<div class="col-md-2 col-sm-6 col-xs-12"></div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<b>From:</b>
					<div class="input-group date">
						<div class="input-group-addon">
							<i class="fa fa-calendar"></i>
						</div>
						<input type="text" readonly placeholder="select from date" value="<?=$date1?>" style="cursor:pointer" name="date1" class="form-control pull-right datepicker">
					</div>
				</div>
				<div class="col-md-3 col-sm-6 col-xs-12">
					<b>To:</b>
					<div class="input-group date">
						<div class="input-group-addon">
							<i class="fa fa-calendar"></i>
						</div>
						<input type="text" readonly placeholder="select to date" style="cursor:pointer" value="<?=$date2?>" name="date2" class="form-control pull-right datepicker">
					</div>
				</div>
				<div class="col-md-2 col-sm-6 col-xs-12">
					<b>Filter By Status:</b>
					<div class="input-group date">
						<select name="status" class="form-control">
							<option value="">SELECT ALL</option>
							<option value="PENDING" <?=$status=="PENDING"?"selected":""?>>PENDING</option>
							<option value="PAID" <?=$status=="PAID"?"selected":""?>>PAID</option>
							<option value="CANCELLED" <?=$status=="CANCELLED"?"selected":""?>>CANCELLED</option>
						</select>
					</div>
				</div>
				<!--
				<div class="col-md-2 col-sm-6 col-xs-12">
					<b>Filter By Service Type:</b>
					<div class="input-group date">
						<select name="s_type" class="form-control">
							<option value="">ALL SERVICE TYPES</option>
							<option value="MAINTENANCE" <?=$type=="MAINTENANCE"?"selected":""?>>MAINTENANCE</option>
							<option value="REPAIR" <?=$type=="REPAIR"?"selected":""?>>REPAIR</option>
						</select>
					</div>
				</div>
				
				-->
				<div class="col-md-2 col-sm-6 col-xs-12">
					<div class="input-group date"><br>
						<button type="submit" class="btn btn-primary"><i class="fa fa-refresh"></i> Refresh</button>
					</div>
				</div>
			</div>
			
			<?php echo form_close(); ?>
			
			<hr style="margin-top:0px;margin-bottom:15px;border-top:2px solid #eee">
					<table class="table table-striped table-hover table-bordered rwd-table" id="dataTableId">
						<thead>
							<tr>
								<th style="width: 10px">SN</th>
								<th>Invoice ID</th>
								<th>Request ID</th>
								<th>Customer Names</th>
								<th style="text-align:right">Invoice Amount &#8358;</th>
								<th style="text-align:right">Paid Amount &#8358;</th>
								<th style="text-align:right">Balance Amount &#8358;</th>
								<th>Payment Status</th>
								<th>Invoice Date</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
			<?
					$i=1;
					if(count($services)>0){
						foreach($services as $rowz){
			?>
							<span style="display:none" id="description<?=$rowz['id']?>"><?=$rowz['description']?></span>
							
							<span style="display:none" id="discount_amount<?=$rowz['id']?>"><?=$this->utilities->format_number($rowz['discount_amount'])?></span>
							<span style="display:none" id="total_amount<?=$rowz['id']?>"><?=$this->utilities->format_number($rowz['total_amount'])?></span>
							<span style="display:none" id="balance_amount<?=$rowz['id']?>"><?=$this->utilities->format_number($rowz['amount_owed'])?></span>
							<span style="display:none" id="createdby<?=$rowz['id']?>"><?=$rowz['generatedby']?></span>
							<span style="display:none" id="record_date<?=$rowz['id']?>"><?=$this->utilities->system_date($rowz['record_date'])?></span>
							
							<tr id="rholder<?=$rowz['id']?>">
								<td data-th="#"><?=$i?></td>
								<td data-th="Invoice ID"><a style="cursor:pointer;text-decoration:underline" data-toggle="modal" data-target="#myModal" title="click to view detail" onclick="showPaymentModal('<?=$rowz['id']?>')">000<?=$rowz['id']?></a></td>
								<td data-th="Request ID" id="service_request_id<?=$rowz['id']?>">000<?=$rowz['service_request_id']?></td>
								<td data-th="Customers" id="customers<?=$rowz['id']?>"><?=$rowz['usernames']?></td>
								<td data-th="Total Amount" id="invoice_amount<?=$rowz['id']?>" style="text-align:right"><?=$this->utilities->format_number($rowz['invoice_amount'])?></td>
								<td data-th="Paid Amount" id="paid_amount<?=$rowz['id']?>" style="text-align:right"><?=$this->utilities->format_number($rowz['paid_amount'])?></td>
								<td data-th="Balance" style="text-align:right"><?=$this->utilities->format_number($rowz['amount_owed'])?></td>
								<td data-th="Status" id="i_status<?=$rowz['id']?>"><?=$this->utilities->get_status_style($rowz['i_status'])?></td>
								<td data-th="start date" id="createdon<?=$rowz['id']?>"><?=$this->utilities->system_date($rowz['createdon'],2)?></td>
								<td>
									
									<div class="btn-group pull-right">
									  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">Action
										<span class="caret"></span>
										<span class="sr-only">Toggle Dropdown</span>
									  </button>
									  <ul class="dropdown-menu" role="menu">
										<li>
											<a style="cursor:pointer" data-toggle="modal" data-target="#myModal" title="click to view detail" onclick="showPaymentModal('<?=$rowz['id']?>')">View Details</a>
										</li>
										<li>
											<a style="cursor:pointer" data-toggle="modal" data-target="#myModal2" onclick="showPaymentModal2('<?=$rowz['id']?>')" title="click to view payment history">Payment History</a>
										</li>
										<li>
											<a href="<?=base_url("cpanel/request_details/".$rowz['service_request_id'])?>" title="view service request" >View Service Request</a>
										</li>
										<li class="divider"></li>
										<li><a href="<?=base_url("cpanel/print_invoice/?id=".$rowz['id'])?>" target="_blank">Print Invoice</a></li>
									  </ul>
									</div>
									
									<!--
									<a style="cursor:pointer" class="btn btn-xs btn-info" data-toggle="modal" data-target="#myModal" id="showExampleModal" title="click to edit" onclick="showPaymentModal('<?=$rowz['id']?>')"><i class="fa fa-eye"></i> Details</a>
									-->
								</td>
							</tr>
			<?
						$i++;
						}
					}
			?>
					</tbody></table><br/><br/><br/>
				
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
<script type="text/javascript">
	function showPaymentModal2(id){
		$("#myModalLabel2").html("Payments History For Invoice #0000"+id);
		$('#loadingimg').show();//indicate to user loading img
		var loadUrl="<?=base_url("cpanel/get_payments_history/?invoiceid=")?>"+id;
		//start the ajax
		$.ajax({
			url: loadUrl,
			type: "POST",
			success: function (html) {
				$('#loadingimg').hide();
				$('#display_payments').html(html);
			},
			error: function(xhr, textStatus, errorThrown) {
				alert('An error occurred! ' + errorThrown);
				$('#loadingimg').hide();
			}									
		});//end of ajax
	}
	function showPaymentModal(id){
		$("#myModalLabel").html("Invoice Details (ID: 0000"+id+")");
		$("#total_amount").html("");	$("#total_amount").html("&#8358;"+$("#total_amount"+id).html());
		$("#submitted_on").html("");	$("#submitted_on").html($("#submitted_on"+id).html());
		$("#paid_amount").html("");	$("#paid_amount").html("&#8358;"+$("#paid_amount"+id).html());
		$("#i_status").html("");	$("#i_status").html($("#i_status"+id).html());
		$("#service_request_id").html("");	$("#service_request_id").html($("#service_request_id"+id).html());
		$("#record_date").html("");	$("#record_date").html($("#record_date"+id).html());
		$("#discount_amount").html("");	$("#discount_amount").html("&#8358;"+$("#discount_amount"+id).html());
		$("#invoice_amount").html("");	$("#invoice_amount").html("&#8358;"+$("#invoice_amount"+id).html());
		$("#balance_amount").html("");	$("#balance_amount").html("&#8358;"+$("#balance_amount"+id).html());
		$("#generator_kva").html("");	$("#generator_kva").html($("#generator_kva"+id).html());
		$("#createdon").html("");	$("#createdon").html($("#createdon"+id).html());
		$("#createdby").html("");	$("#createdby").html($("#createdby"+id).html());
		$("#description").html("");	$("#description").html($("#description"+id).html());
		$("#btn_print").attr("href","<?=base_url('cpanel/print_invoice/?id=')?>"+id);
	}
	$('#btnnotify').click(function(e){
		//e.preventDefault();
		$('#notify').val(1);
		$("#frmRegister").submit();
	});
</script>
	  
<link href="<?php echo base_url()?>assets/user/plugins/parsley/parsley.css" rel="stylesheet">
<script src="<?php echo base_url()?>assets/user/plugins/parsley/parsley.min.js"></script>